### ISSUE TITLE
SPIFFS file system?

### ISSUE THREAD

**Issue by ModischFabrications** [ModischFabrications/Verdandi#13]
We have some kind of file system on the ESP8266:

https://tttapa.github.io/ESP8266/Chap11%20-%20SPIFFS.html

This should also enable us to send files for #2 and could make #10 obsolete.

**Comment by ModischFabrications** [comment]
https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino

**Comment by ModischFabrications** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPIFFS](https://trello.com/c/m3CK6rFe/40-spiffs)

**Comment by LukPopp0** [comment]
Filesystem layout ESP8266:
https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#flash-layout

Uploading files to the ESP8266 with platformio:
http://docs.platformio.org/en/latest/platforms/espressif8266.html#uploading-files-to-file-system-spiffs

**Comment by LukPopp0** [comment]
Upload data folder by pressing "Uploading file system image" in the PIO UI
