### ISSUE TITLE
Implement LED controller

### ISSUE THREAD

**Issue by LukPopp0** [ModischFabrications/Verdandi#14]

**Comment by ModischFabrications** [comment]
connect flashing to error logging?

**Comment by LukPopp0** [comment]
- 3 Arrays (len: N_LEDS) that contain the fading pre-multiplier for every led for each watch hand
:arrow_right: call function for each watch hand and pass the respecting array
- go through all arrays and for each led sum up all the fading multipliers (0.9H+0.2M+0.4S = 1.5) 
- final color is: (0.9/1.5)H + (0.2/1.5)M + (0.4/1.5)S

**Comment by LukPopp0** [comment]
wipe watch hand arrays each time

**Comment by ModischFabrications** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LED controller](https://trello.com/c/zKDyTbYG/41-led-controller)
