### ISSUE TITLE
Config Portal

### ISSUE THREAD

**Issue by ModischFabrications** [ModischFabrications/Verdandi#2]
Make all runtime parameters user selectable via website.

**Comment by ModischFabrications** [comment]
load values from ESP instead of using hardcoded defaults. This could eventually lead to synchronized states on multiple clients (if we are fine with repeated polling for new values)

**Comment by ModischFabrications** [comment]
information flow could be done by using

1. callback-style function pointers -> `typedef void (*f_listener)();`
2. MVC-like controller that decouples network from LEDs -> `main.onColorSet(FASTLED::Color color)`

**Comment by ModischFabrications** [comment]
1 is clean software, two is probably easier

**Comment by ModischFabrications** [comment]
check ranges in frontend as well as backend

**Comment by LukPopp0** [comment]
Blur website until the config request is finished

**Comment by LukPopp0** [comment]
ArduinoJSON: https://arduinojson.org/book/serialization_tutorial6.pdf#page=10 
Use for answering config request
