### ISSUE TITLE
NTP time fetching

### ISSUE THREAD

**Issue by ModischFabrications** [ModischFabrications/Verdandi#3]
Fetch time from NTP instead of polling an API as that will ensure perfect uptime and nice parsing.
https://lastminuteengineers.com/esp8266-ntp-server-date-time-tutorial/

NTP Url could be exchanged at runtime -> #2 

Check time delta whenever fetching to observe the drift (not necessary but interesting)

**Comment by ModischFabrications** [comment]
Initial idea was fetching time from an API like worldtimeapi.org, but they a not even close to being comparably reliable to NTP. Having a nice NTP-lib for the arduino also makes parsing very easy.

**Comment by ModischFabrications** [comment]
This makes discussions about formats like ISO 8602 obsolete, as components are fetched via function call instead of parsing them.

**Comment by ModischFabrications** [comment]
Implemented around commit 7eb13efac56a3a1c88d6468b45181947873fe144.

**Comment by ModischFabrications** [comment]
https://github.com/esp8266/Arduino/blob/master/libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino

**Comment by ModischFabrications** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NTP](https://trello.com/c/DCYnHPW2/42-ntp)

**Comment by ModischFabrications** [comment]
Update interval only a "#define", so not possible?

**Comment by ModischFabrications** [comment]
callback possible to display "no wlan" until the first NTP call succeded.

**Comment by LukPopp0** [comment]
Dont display time until first ntp fetch complete -> listener

**Comment by LukPopp0** [comment]
Timezone info on stackoverflow with helpful links: https://stackoverflow.com/tags/timezone/info
