### ISSUE TITLE
nightmode ignores times

### ISSUE THREAD

**Issue by ModischFabrications** [ModischFabrications/Verdandi#33]
boolean flag `nightmode` is respected, but times are ignored. It seems like the comparison is broken.

**Comment by ModischFabrications** [comment]
time comparison looks fine, are we sure that the values are transmitted correctly @LukPopp0 ?

**Comment by LukPopp0** [comment]
closed with commit 69e3309e0cc869061b10706eb3c4e2bc862ae14a
