### ISSUE TITLE
const everything

### ISSUE THREAD

**Issue by ModischFabrications** [ModischFabrications/Verdandi#4]
Constant values are optimized a lot better, find out how many costs you can add to this code.

**Comment by LukPopp0** [comment]
Flashstring everything

**Comment by ModischFabrications** [comment]
No need for `const void method()`, while allowed, void returns are always const by default. 

`void method() const` works only for member functions (of classes) and has no use for us either. 

http://www.cplusplus.com/forum/general/12087/

**Comment by ModischFabrications** [comment]
current usage for comparison: 
RAM:   [====      ]  41.7% (used 34136 bytes from 81920 bytes)
Flash: [====      ]  40.5% (used 388596 bytes from 958448 bytes)

It might not be modified either way, but it would be nice to see.
