### ISSUE TITLE
Error output/logging?

### ISSUE THREAD

**Issue by ModischFabrications** [ModischFabrications/Verdandi#7]
New URL "/debug" with hardware information and a log list? 

This is probably a bit to big for an embedded system and will definitely taint all modules, but it could also make debugging a lot easier.

**Comment by ModischFabrications** [comment]
Include LEDs as output? "All-red" for error, yellow for warning? Flashing?

**Comment by ModischFabrications** [comment]
use a ring buffer, URL is good, no persistence

**Comment by ModischFabrications** [comment]
Implemented similar to #2

**Comment by ModischFabrications** [comment]
"Hey, it seems like there are errors. [Look at the logs](/debug) "

**Comment by ModischFabrications** [comment]
Trim log messages on "add(String entry)"

**Comment by ModischFabrications** [comment]
backend finished, needs to implemented in frontend

**Comment by ModischFabrications** [comment]
https://www.w3schools.com/html/html_lists.asp

**Comment by ModischFabrications** [comment]
Ordered HTML List type table looks good

**Comment by LukPopp0** [comment]
TODO: add index of ringbuffer and order it in the frontend

**Comment by ModischFabrications** [comment]
closing ab9c0d7b965c4ea36dc782d3939905ca2bf90c49
